[package]
name = "cosmwasm-testing-util"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "=1.2"
cosmwasm-schema = "=1.2"
cosmwasm-crypto = "=1.2"
cosmwasm-vm = { version = "=1.2", features = ["stargate"] }
bech32 = "0.9.1"
